#!/usr/bin/env python
# coding: utf-8

# See README for details. 

# import required packages
import numpy as np
from astropy.io import fits
from astropy import units, constants
import warnings
import time
import os
import warnings
import yaml
import logging
import matplotlib.pyplot as plt
from matplotlib import colors
import sys

from ps_eor import datacube, pspec, psutil

logger = logging.getLogger(__name__)

## General parameters
# These are general parameters describing the dataset and the instrument (e.g., integration time, k-bins, station diameter).
# 21cm rest-frame frequency
nu0 = 1420 * units.MHz

## Useful fonctions

# Define four useful functions:
# 1. `plot_ps2d` to plot the cylindrical power spectrum
# 2. `get_ps_gen_square` to bin the cylindrical power spectrum generated by `ps_eor`
# 3. `set_kpar_max` which selects the range of k_parallel over which to output ps2d results
# 4. `reduce_file` which selects a set of frequency channels in an existing FITS file and saves the output as a new FITS file.


def plot_ps2d(
        pspec_2d, kperp_bins, kpara_bins, dimless=False,
        label=r'P($k_\parallel$,$k_\perp$) [(Jy/beam)$^2$ Mpc$^3$]',
        norm=None, title=None, cmap='viridis', ax=None, little_h=False,
    ):
    """
    Method to plot cylindrical power spectrum with logarithmic colorbar.

    Parameters
    ----------
        pspec_2d: 2D array of floats
            Array containing the cylindrical power spectrum.
            Shape: (nkperp, nkpara).
        kperp_bins: array of floats
            Array containing the k_perpendicular bins used
            to compute the cylindrical power spectrum.
            Size: nkperp.
        kpara_bins: array of floats
            Array containing the k_parallel bins used
            to compute the cylindrical power spectrum.
            Size: nkpara.  
        dimless: boolean
            Whether the power spectrum is dimensionless or not.
            Default: False.
        label: str
            Label for the colorbar.
            Default is P(k) in (Jy/beam)2 Mpc3.
        norm: matplotlib.colors.Normalize object.
        title: str
            Title for the axis.
            Default is None.
        cmap: str
            Matplotlib colormap to use.
            Default is viridis.
        ax: matplotlib.axes object
            Axis to plot the figure on.
            Default is None (new figure and axis are generated).
        little_h: boolean
            Whether to use little_h units or not.
            Default is False.


    """

    kperp_bins = np.atleast_1d(kperp_bins)
    kpara_bins = np.atleast_1d(kpara_bins)
    assert np.shape(pspec_2d) == (kperp_bins.size, kpara_bins.size), \
        "Input pspec must have shape (kperp_bins.size, kpara_bins.size)."
    if np.any(pspec_2d < 0):
        warnings.warn(
            'There are negative values in your pspec. '
            'Absolute value will be used for the figure.'
        )
        pspec_2d = np.abs(pspec_2d)
    h = 'h' if little_h else ''

    existing_axis = True
    if ax is None:
        fig, ax = plt.subplots(1, 1,)
        existing_axis = False
    if dimless:
        k = np.sqrt(kperp_bins[None, :]**2 + kpara_bins[:, None]**2)
        pspec2d *= k**3 *1./2./np.pi**2
        label = r'$\Delta^2(k)$ [K$^2$]'

    im = ax.pcolor(
        kperp_bins,
        kpara_bins,
        pspec_2d,
        shading='auto',
        cmap=cmap,
        norm=norm,
    )
    if not existing_axis:
        plt.colorbar(im, label=label, ax=ax)
        ax.set_ylabel(fr'k$_\parallel$ [${h}$Mpc$^{{-1}}]$')
        ax.set_xlabel(fr'k$_\perp$ [${h}$Mpc$^{{-1}}]$')
    if title is not None:
        ax.set_title(title)
    
    
def get_ps_gen_square(cube, fmin, **kargs):
    ''' This function return a ps_gen object which will return a power-spectra with the SDC3a binning scheme '''
    z = psutil.freq_to_z((fmin + 7.5) * 1e6)
    du = psutil.k_to_l(0.05, z) / (2 * np.pi)
    umin = du / 2.
    umax = psutil.k_to_l(0.5, z) / (2 * np.pi) + du / 2
    M = int((1 / psutil.k_to_delay(0.05, z)) / 0.1e6)
    ps_builder = pspec.PowerSpectraBuilder()
    ps_gen = ps_builder.get(cube, fmhz_range=[fmin, fmin + 15], du=du, umin=umin, umax=umax, uniform_u_bins=True, **kargs)
    ps_gen.eor.M = M
    ps_gen._compute_delays()
    return ps_gen


def set_kpar_max(ps2d, kpar_max=0.53):
    idx = ps2d.k_par < kpar_max
    return pspec.CylindricalPowerSpectra(ps2d.data[idx], ps2d.err[idx], ps2d.delay[idx], ps2d.el, ps2d.k_per, 
                                         ps2d.k_par[idx], n_eff=ps2d.n_eff[idx])

    
def reduce_file(filename, spw_range):
    """
    Method to select given frequency channels in FITS file.

    Parameters
    ----------
        filename: str
            Path to the FITS files containing the image data (3D).
            Should have units (astropy.units).
        spw_range: array of floats
            List of frequencies to extract from dataset.
    
    Returns
    ------
        hdu
    """
    nf = spw_range.size
    hdu = fits.open(filename)
    nfreqs = hdu[0].header['NAXIS3']
    df = hdu[0].header['CDELT3'] * units.Hz
    fmin = hdu[0].header['CRVAL3'] * units.Hz
    fmax = fmin + df * nfreqs
    freqs = np.arange(fmin.value, fmax.value, step=df.value) * units.Hz
    assert fmin <= spw_range[0].to(units.Hz)
    assert fmax >= spw_range[-1].to(units.Hz)
    assert freqs.size == nfreqs
    inds = np.where((freqs<=spw_range[-1]) & (freqs>=spw_range[0]))[0]
    assert inds.size == nf
    hdu[0].data = hdu[0].data[inds, :, :]
    hdu[0].header['NAXIS3'] = nf
    hdu[0].header['CRVAL3'] = spw_range[0].to(units.Hz).value
    return hdu

    
def main():

    # set up paths        
    config_file = './config/config.yml'
    if os.path.exists(config_file):
        with open(config_file, "r") as f:
            config = yaml.safe_load(f)
    else:
        warnings.warn(f"! Configuration file '{config_file}' not found. Using default settings.", UserWarning)
        config = {}
        
    default_base_path = "../datasets"
    base_path = config.get("data_path")
    if base_path is None:
        warnings.warn(f"! 'data_path' not found in '{config_file}'. Using default path '{default_base_path}'.", UserWarning)
        base_path = default_base_path
    datafolder = base_path # where to find the downloaded data - here, on Azimuth
    
    default_result_path = "../results"
    result_path = config.get("result_path")
    if result_path is None:
        warnings.warn(f"! 'result_path' not found in '{config_file}'. Using default: '{default_result_path}'.", UserWarning)
        result_path = default_result_path

    result_path = os.path.join(result_path, "SWF-008-T1")
    if not os.path.exists(result_path):
        os.makedirs(result_path, exist_ok=True)
    # Add path to save any plots and tables
    save_path = result_path 

    # Set up log file
    if not os.path.exists(f'{result_path}profiling/'):
        os.makedirs(f'{result_path}profiling/', exist_ok=True)
    logging.basicConfig(
        filename=f'{result_path}profiling/SWF-008-T1.log',
        filemode='w',
        level=logging.INFO,
        format="%(message)s",
    )
    logger.info('\nStarted running the workflow.')

    # BINS TO USE FOR HISTOGRAMMING
    
    # k-range
    dkperp = 0.05
    kperp_bins = np.arange(0.05, 0.55, step=dkperp)
    kperp_edges = np.arange(kperp_bins.min()-dkperp/2, kperp_bins.max()+dkperp, dkperp)
    
    dkpara = 0.05
    kpara_bins = np.arange(0.05, 0.55, step=dkperp)
    kpara_edges = np.arange(kpara_bins.min()-dkpara/2, kpara_bins.max()+dkpara, dkpara)
    
    k_mag = np.sqrt(kperp_bins[:, None]**2 + kpara_bins[None, :]**2)
    kmin = np.min(k_mag) / units.Mpc
    kmax = np.max(k_mag) / units.Mpc
    krange = np.linspace(kmin, kmax, 10).value    
    
    # instrument specs
    bmax = 5. * units.km  # maximum baseline
    D_station = (35+40)/2 * units.m  # SKA-Low station diameter

    # details about mock observations
    total_time = 1000. * units.hour  # total observation time
    int_time = 10.*units.second  # integration time
    
    ## Load data cubes from FITS files
    # We choose a limited spectral window to reduce computations:
    
    df = 0.100  # MHz, frequency resolution
    fmin = 166.0  # minimum frequency on the spectral window
    fmax = 180.9  # maximum frequency on the spectral window
    spw_range = np.round(np.arange(fmin, fmax+df, step=df), decimals=2) * units.MHz  # spectral window
    avg_nu = np.mean(spw_range)  # mean frequency over spectral window
    avg_z = nu0/avg_nu - 1.  # mean redshift over spectral window
    lamb_array = constants.c.si / (spw_range.si)  # array of observed wavelengths over spectral window
    
    # Below, we extract the required frequency channels from the input files and save the result as a new fits file which will be fed to `ps_eor`.    

    # REDUCING FILES
    weighting = 'msn'
    
    # PSF
    reduced_psf_file = f'{base_path}All.{weighting}_psf_reduced.fits'
    if os.path.exists(reduced_psf_file):
        # If the reduced file exist, make sure it contains the appropriate frequencies.
        hdu = fits.open(reduced_psf_file)
        du = abs(hdu[0].header['CDELT1'])
        assert hdu[0].data.shape[0] == spw_range.size
        hdu.close()
    else:
        # Else, load full PSF file and reduce
        psffile = f'{base_path}All.{weighting}_psf.fits'
        hdu = reduce_file(psffile, spw_range)
        du = abs(hdu[0].header['CDELT1'])
        npix = hdu[0].data.shape[1]
        # Save to new file
        hdu.writeto(reduced_psf_file, overwrite=True)
        hdu.close()
    
    # IMAGE
    reduced_image_file = f'{base_path}IM1.{weighting}_image_reduced.fits'
    if os.path.exists(reduced_image_file):
        # If the reduced file exist, make sure it contains the appropriate frequencies.
        hdu = fits.open(reduced_image_file)
        assert hdu[0].data.shape[0] == spw_range.size
        hdu.close()
    else:
        # Else, load full image file and reduce.
        imagefile = f'{base_path}IM1.{weighting}_image.fits' # location of the image file downloaded from SKA SDC3 drive
        hdu = reduce_file(imagefile, spw_range)
        hdu.writeto(reduced_image_file, overwrite=True)
    hdu.close()

    # We use `ps_eor` to load the reduced PSF and image files and transform them into visibility cubes:

    t0 = time.time()
    w_cube = datacube.CartWeightCube.load_from_fits_image_and_psf(
        files=[f'{base_path}IM1.{weighting}_image_reduced.fits'],
        files_psf=[f'{base_path}All.{weighting}_psf_reduced.fits'],
        umin=30,
        umax=500,
        theta_fov=np.radians(4.),
        int_time=int_time.to(units.s).value,
        total_time=total_time.to(units.s).value,
        use_wscnormf=False, # use pSF and not WSCNORMF to normalise the visibilities
        window_function=datacube.WindowFunction('boxcar')
    )
    t1 = time.time()
    logger.info(f'Conversion to visibility cube took {(t1-t0)/60.:.2f} minutes.')
        
    ## Power spectra
    
    # Here, we compute the power spectrum from the image cube IM1 and the PSF with `ps_eor`.    
    
    # Create a Cylindrically averaged PS and plot
    ps_gen_sq = get_ps_gen_square(w_cube, fmin, primary_beam='ska_low', window_fct='hann', ft_method='nudft', rmean_freqs=False)
    ps2d = set_kpar_max(ps_gen_sq.get_ps2d(w_cube))

    fig, ax = plt.subplots(1, 1, figsize=(4.5, 5))
    plot_ps2d(
        ps2d.data, 
        kperp_bins, kpara_bins,
        cmap='Spectral_r', norm=colors.LogNorm(vmin=7e-3, vmax=7e-1), little_h=True,
        label=r'$P(k_\perp, k_\parallel)\, [\mathrm{K}^2 h^{-3} \mathrm{Mpc}^3]$',
        ax=ax,
    )
    fig.tight_layout()
    fig.savefig(os.path.join(save_path, 'cylindrical_eor_ps_from_image.png'), dpi = 300)  # Save the figure if uncommented
    logger.info(f'{save_path}cylindrical_eor_ps_from_image.png figure saved.')
    
    logger.info('Finished.')

if __name__ == '__main__':
    main()
